# Generated by Django 4.1.5 on 2023-02-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='photo',
            field=models.ImageField(blank=True, upload_to='genres/'),
        ),
    ]
